version: '3'

services:

  node-1:
    container_name: node-1
    image: "raft-node:latest"
    ports:
      - "3000:3000"
      - "50051:50051"
    environment:
      LEADER_ID: node-1
      PEER_IDS: node-2,node-3
    networks:
      - app-network

  node-2:
    container_name: node-2
    image: "raft-node:latest"
    ports:
      - "3001:3000"
      - "50052:50051"
    depends_on:
      - node-1
    environment:
      LEADER_ID: node-2
      PEER_IDS: node-1,node-3
    networks:
      - app-network

  node-3:
    container_name: node-3
    image: "raft-node:latest"
    ports:
      - "3002:3000"
      - "50053:50051"
    depends_on:
      - node-1
      - node-2
    environment:
      LEADER_ID: node-3
      PEER_IDS: node-1,node-2
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

